//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afbeelding
    {
        public Afbeelding()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public byte[] Afbeelding1 { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
