//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BestelRegel
    {
        public int BestellingId { get; set; }
        public int EventId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Bestelling Bestelling { get; set; }
        public virtual Event Event { get; set; }
    }
}
