//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        public Bestelling()
        {
            this.BestelRegels = new HashSet<BestelRegel>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> Betaald { get; set; }
        public Nullable<double> TotaalPrijs { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string EmailAdres { get; set; }
    
        public virtual ICollection<BestelRegel> BestelRegels { get; set; }
    }
}
