//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombiDeal
    {
        public int Id { get; set; }
        public Nullable<int> Percentage { get; set; }
        public int Event2 { get; set; }
        public int Event1 { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Event Event3 { get; set; }
    }
}
