//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int Id { get; set; }
        public string Regisseur { get; set; }
        public string Acteur { get; set; }
        public Nullable<int> Jaar { get; set; }
        public Nullable<int> Aantal { get; set; }
        public int EventId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
