//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highlight
    {
        public Nullable<int> Id { get; set; }
        public int Slide1 { get; set; }
        public Nullable<int> Slide2 { get; set; }
        public Nullable<int> Slide3 { get; set; }
        public Nullable<int> Slide4 { get; set; }
        public Nullable<int> Slide5 { get; set; }
    
        public virtual Slide Slide { get; set; }
        public virtual Slide Slide6 { get; set; }
        public virtual Slide Slide7 { get; set; }
        public virtual Slide Slide8 { get; set; }
        public virtual Slide Slide9 { get; set; }
    }
}
