//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHFF_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Medewerker
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Gebruikersnaam is nodig!")]
        [Display(Name = "Gebruikers Naam")]
        public string Gebruikersnaam { get; set; }
        [Required(ErrorMessage = "Wachtwoord is nodig!")]
        [Display(Name = "Wachtwoord")]
        public string Wachtwoord { get; set; }
    }
}
